# Generated by Django 3.2.14 on 2022-08-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_item_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
